import random
import os
from pysat.solvers import Glucose3

def generate_dummy_file(filename, num_vars, num_clauses):
    clauses = []
    
    for _ in range(num_clauses):
        vars_in_clause = random.sample(range(1, num_vars + 1), 3)
        clause = [v if random.choice([True, False]) else -v for v in vars_in_clause]
        clauses.append(clause)
        
    with Glucose3(bootstrap_with=clauses) as solver:
        models = list(solver.enum_models())
        solution_count = len(models)
        
    with open(filename, 'w') as f:
        f.write(f"c This Formular a dummy for testing purposes\n")
        f.write(f"c generated by python test-builder\n")
        f.write(f"p cnf {num_vars} {num_clauses}\n")
        
        for c in clauses:
            f.write(f"{c[0]} {c[1]} {c[2]} 0\n")
            
        f.write("%\n0\nsolution\n")
        f.write(f"{solution_count}\n")

output_dir = "../test_instances"
os.makedirs(output_dir, exist_ok=True)

print("Generating Test Data...")
for i in range(1, 21):
    filename = f"{output_dir}/dummy_15vars_{i}.cnf"
    generate_dummy_file(filename, num_vars=15, num_clauses=50)
    print(f"Saved: {filename}")

print("Done!")